### ISSUE TITLE
[MAJOR] Update workbox to v6

### ISSUE THREAD

**Issue by Jeevan-Kishore** [quintype/quintype-node-framework#201]
## Context

Our workbox is at `const workboxVersion = "2.1.1";` and is about 4 major versions behind the current.

## Resources 

- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v2
- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v3
- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v4
- https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v5

## Todo

1. Analyse & document breaking changes 
2. Bump all prerequisites such as node, webpack to needed versions
3. Perform updated to bump to the current version
4. Validate stability and expected functionality

**Comment by EnKrypt** [comment]
Aditional efforts: If there is a waiting service worker registration, and there is an ajax navigation about to happen, hijack that event and force a reload so that the new service worker can become active.

**Comment by DivyaPrithvi** [comment]
Test scenarios:
- [ ] Unregister service worker and do a page refresh, the data should be loaded on the page
- [ ] Verify that on unregistering service worker and doing a page refresh, service worker should be re-installed and serve data
- [ ] Verify that on the first page load on app is served from the server on network tab
- [ ] Verify that on second and further load, the page is served from the service worker instead of memory/disk cache of the browser on network tab
- [ ] Verify that any page loaded earlier is served from the service worker when the network is not available
- [ ] Verify that the app must be served when there is no network, at least the header and footer should be displayed
- [ ] Verify that there is no page/layout break on Desktop (homepage,story page, section page, tag page, author page and magazine page)
- [ ] Verify that there is no page/layout break on mobile (homepage,story page, section page, tag page, author page and magazine page)
- [ ] Verify that there is no page/layout break on iPad/iPad Pro (homepage,story page, section page, tag page, author page and magazine page)
